### ISSUE TITLE
Provide a world for the gazebo simulation

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#104]
## Desired behavior
Provide a world for the simulation

Which world? To discuss here

**Comment by olmerg** [comment]
This worlds can generate nice renders [aws robomaker](https://github.com/aws-robotics)

**Comment by marcoshuck** [comment]
https://app.gazebosim.org/fuel/worlds has tons of worlds. I personally really like the Cave World: https://app.gazebosim.org/OpenRobotics/fuel/worlds/Cave%20World

**Comment by marcoshuck** [comment]
It might be a bit challenging for our little friend, maybe some of the Urban worlds are better suited for andino: https://app.gazebosim.org/OpenRobotics/fuel/worlds/Urban%20Circuit%20Practice%2001
