### ISSUE TITLE
Allow to load custom configuration for the description

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#135]
### Context

Nowadays the configuration files that describe the robot are located at:
https://github.com/Ekumen-OS/andino/tree/humble/andino_description/config/andino

However if the user wanted to have it a bit different; `motors` added in a different manner, `lidar` displaced and connected somwhere else, `base` with different size; they should create their own URDF files as the configuration files are harcoded within the [`xacro` file](https://github.com/Ekumen-OS/andino/blob/humble/andino_description/urdf/andino.urdf.xacro)

### Proposal
- Modify the xacro to receive by argument the path to the configuration files
- Use as default the current files if no argument is passed down to the xacro files.
- Modify the launch file to accept passing the path to the configuration yaml.

### Also!
 - Update documentation

**Comment by JesusSilvaUtrera** [comment]
@francocipollone We should close this issue if it is already solved and merged

**Comment by jballoffet** [comment]
@lneumarkt, are you currently working on this? No worries if not, just let us know since @JesusSilvaUtrera was considering picking it up. Thanks!

**Comment by lneumarkt** [comment]
I'm not working on is. Feel free to pick it up

**Comment by jballoffet** [comment]
Got it, thanks @lneumarkt for the prompt response!

**Comment by JesusSilvaUtrera** [comment]
Thanks @lneumarkt for the response, I will take this issue.
