### ISSUE TITLE
Move hardware interface plugin configuration to a config file.

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#136]
Depends on #135 

### Context
The configuration of the andino hardware interface is harcoded in the urdf

https://github.com/Ekumen-OS/andino/blob/70a9ad6d65089c1b999859ed6a5113fb0d23bdd0/andino_description/urdf/include/andino_control.urdf.xacro#L6-L15

### Proposal
 - Request a configuration yaml for the ros control configuration

**Comment by JesusSilvaUtrera** [comment]
As this issue is related to #135, I will take it as well ans try to submit a PR with both issues.

**Comment by JesusSilvaUtrera** [comment]
@francocipollone Do you think it would be better to move the `andino_control.urdf.xacro` to `andino_control`? I think it is better to have all the xacro files together, if we do that we would create a dependency between `andino_description` and `andino_control`, and also we would need to add dependencies like xacro to `andino_control`.

**Comment by francocipollone** [comment]
> @francocipollone Do you think it would be better to move the `andino_control.urdf.xacro` to `andino_control`? I think it is better to have all the xacro files together, if we do that we would create a dependency between `andino_description` and `andino_control`, and also we would need to add dependencies like xacro to `andino_control`.

Let's keep it in andino_description for now, thanks for checking

**Comment by JesusSilvaUtrera** [comment]
@francocipollone I just noticed that this was merged but the issue was not closed, JIC you want to close it.
