### ISSUE TITLE
Rename andino_gazebo package to andino_gz_classic

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#152]
### Context
- gazebo classic -> https://classic.gazebosim.org/
- gazebo -> https://gazebosim.org/home

### Summary

In order to keep a correct nomenclature we should rename the `andino_gazebo` package and fix all the appearances of this.
The simulation we have here isn't using the `gazebo` simulator but the `gazebo classic` one. In order to allow a `gazebo` simulator to happen we need to fix this colliding name.

### Options

- andino_gz_classic
- andino_gazebo_classic  -> Probably too long

In the future a `gazebo` simulation will be:
- andino_gz

**Comment by francocipollone** [comment]
@jballoffet any preference?

**Comment by jballoffet** [comment]
andino_gz and andino_gz_classic SGTM!

**Comment by agalbachicar** [comment]
This is a breaking change for https://github.com/Ekumen-OS/andino_integration_tests
Not blocking, just tracking :)

**Comment by francocipollone** [comment]
> This is a breaking change for https://github.com/Ekumen-OS/andino_integration_tests Not blocking, just tracking :)

Yeah I got you guys in mind
