### ISSUE TITLE
Adds camera_info yaml file

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#169]
### Summary

When launching the camera we are not passing a yaml with the description of the camera's intrinsics

https://github.com/Ekumen-OS/andino/blob/024b6943e5813c2b555b3f74e0e4e97f8ed21cba/andino_bringup/launch/camera.launch.py#L34-L46

### Notes

- https://navigation.ros.org/tutorials/docs/camera_calibration.html#overview
- https://gitlab.com/boldhearts/ros2_v4l2_camera
- https://github.com/tier4/ros2_v4l2_camera/blob/87d0ff0d24302124ee9a4b8e00ad6d675446b2e3/launch/v4l2_camera.launch.py#L119-L120

### Definition of done

 - [ ] Adds a default yaml file descringin camera intrinsic.
 - [ ] Adds documentation about how to calibrate the camera if needed.

**Comment by JesusSilvaUtrera** [comment]
I will take care of this issue

**Comment by JesusSilvaUtrera** [comment]
I have created this [PR](https://github.com/Ekumen-OS/andino/pull/231) @agalbachicar
