### ISSUE TITLE
Arduino Firmware - Command "o" not working

### ISSUE THREAD

**Issue by german-e-mas** [Ekumen-OS/andino#184]
## Description
After compiling and uploading the [andino_firmware](https://github.com/Ekumen-OS/andino/tree/humble/andino_firmware) into the Arduino, the `o` command did not work.

Commands such as `m 255 255` were correctly interpreted. The speed was also properly controlled (`128` was half as fast, for example). But the `o` command did nothing. It did not move the motors.

## Environment
- https://github.com/Ekumen-OS/andino/tree/humble/andino_firmware

**Comment by jballoffet** [comment]
Thanks @german-e-mas for reporting this issue!

I confirm that I am able to reproduce the issue locally. I will dive into this as part of the work that I'm currently doing related to refactoring the code related to the commands and the application main loop (https://github.com/Ekumen-OS/andino/blob/humble/andino_firmware/src/app.cpp).

Thank you!
