### ISSUE TITLE
Update connections diagram

### ISSUE THREAD

**Issue by JesusSilvaUtrera** [Ekumen-OS/andino#239]
## Desired behavior
The connections diagram doesn't include all the required parts and it is out-of-date, so it would be nice to update it with the latest changes to ease the assembly process.

## Implementation suggestion
Several considerations:
- The encoders and the motors are the same piece, so they should be together.
- The Raspberry is not included in the diagram
- Add the power part well explained, replacing the potato.
- The Arduino UNO should be replaced by an Arduino Nano (optional but the most used is the Nano for this robot)
- Add the LiDAR (optional as its wiring is not something too hard)

**Comment by JesusSilvaUtrera** [comment]
To keep the issue updated, I am creating 3 diagrams in Google Drawings, one with the Arduino connections, the second with Raspberry Pi connections and the third for Power connections. I think this way is easier to follow the diagrams and then just connects the different diagrams into the final robot.

They won't be finished until I test them assembling my own robot.

**Comment by francocipollone** [comment]
> To keep the issue updated, I am creating 3 diagrams in Google Drawings, one with the Arduino connections, the second with Raspberry Pi connections and the third for Power connections. I think this way is easier to follow the diagrams and then just connects the different diagrams into the final robot.
> 
> They won't be finished until I test them assembling my own robot.

Sounds good!
