### ISSUE TITLE
Add Jazzy support

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#266]
### Summary

- [x] Create Jazzy branch
- [ ] Create docker setup for Jazzy
- [ ] Migrate packages to use ROS Jazzy
- [ ] Deprecate andino_gz_classic package
- [ ] Test on real robot.

**Comment by JesusSilvaUtrera** [comment]
@francocipollone The PR adding Jazzy support was merged so this issue can be closed
