### ISSUE TITLE
FAIL TO 'colcon build' THE FIRST TIME

### ISSUE THREAD

**Issue by thanhtruongphan** [Ekumen-OS/andino#272]
Hello everyone! 👋

I just tried to download andino_repositories, and follow the README.md instructions to install. 

But I have some problems when I use _**colcon build**_ 

1. When I ```colcon build``` the first time: 
>>>![image](https://github.com/user-attachments/assets/36ea6ae8-c6c9-45aa-b71d-4445d39ea859)

I solved by ```sudo apt install ros-humble-ros2-control```

2. When I ```colcon build``` the second time: 
>>> ![Screenshot 2024-10-27 155120](https://github.com/user-attachments/assets/dc058036-a98c-43d5-a528-fe0c1eb3aa87)

I solved by ```sudo apt install ros-humble-ament-cmake-clang-format```

3. When I ```colcon build``` the third time: 
>>>![Screenshot 2024-10-27 155201](https://github.com/user-attachments/assets/d0a8a6e7-c721-4fc3-9191-d93a9300451b)

I solved by ```sudo apt install libserial-dev```

4. When I ```colcon build``` the fourth time: 
>>>![Screenshot 2024-10-27 155224](https://github.com/user-attachments/assets/74313f14-0297-451c-88d5-9b0847b089d4)

I solved by ```sudo apt-get install libgflags-dev```

5. When I ```colcon build``` the fifth time: 
>>>![Screenshot 2024-10-27 155256](https://github.com/user-attachments/assets/6e8a6c21-4897-4385-8fe1-5db82beb6d57)

... and now I don't know how to solve it. 

Help me, pls.

Thank you all so much, and have a nice day! 🥹

**Comment by thanhtruongphan** [comment]
UPDATE: 

I tried to mode the line 12 and It's OK now.
>>![image](https://github.com/user-attachments/assets/1acf9507-e0a1-4451-bf2f-9406ad93d2e8)

result: 
>>>>>![image](https://github.com/user-attachments/assets/d1009786-075d-4549-abaf-6af6dbbded49)

**Comment by thanhtruongphan** [comment]
and in SBC: 
![image](https://github.com/user-attachments/assets/20d97ab9-d8a5-4578-aa65-96717461fba7)

**Comment by francocipollone** [comment]
Hey @thanhtruongphan , thanks for the issue creation. 

1. I feel like the issues with the stuff not installed is due to some missing rosdep install: e.g: typically `rosdep install --from-paths src -y -i`

2. Regarding the issues and the modifications to the CMakeLists file you are doing. It is odd and not happening on my end last time a built everything (I am going to try asap when I return from a trip). Could you share your setup? e.g: OS / hardware/ etc

**Comment by thanhtruongphan** [comment]
yeah! 
you're right! 

after ```sudo rosdep init``` and ```rosdep update```, I forget to ```rosdep install --from-paths src -y -i``` 😄

probably because of the errors in the previous project that made me stupid.

anyway, thank you so much for your reply.

have a nice day 🥹
