### ISSUE TITLE
[Simulation] Gazebo ROS control crashes the robot

### ISSUE THREAD

**Issue by stevendes** [Ekumen-OS/andino#30]
### Summary

Using Gazebo ROS Control with the current robot configuration sometimes crashes the robot under specific movements, high values for the PID, or high-velocity commands being sent.

![227820811-9ccda818-f486-4715-bd65-88ecee9d62de](https://user-images.githubusercontent.com/53347092/230792258-2e4e3e27-875d-4323-806d-0bed9d453ecc.png)

Different mass values improve the behavior, indicating that it could be an issue with the Inertia values and how Gazebo ROS control interacts.
  
### Definition of done
 - [ ] Gazebo ROS control works as expected.

**Comment by francocipollone** [comment]
Closing as noetic isn't supported anymore
