### ISSUE TITLE
[URDF] Wheel Axis are not aligned with base_link

### ISSUE THREAD

**Issue by stevendes** [Ekumen-OS/andino#31]
### Summary

The current implementation of the Carpincho URDF has an offset between `base_link` and the `front_right_wheel` and `front_left_wheel`  axis, this influences localization since the robot movement also gets affected by that offset.

The fix would be to modify the position of `base_link` to be between the wheels, sharing the same axis.

![Screenshot from 2023-04-09 15-24-38](https://user-images.githubusercontent.com/53347092/230792834-ce577392-e7c9-4d00-86ac-650ebb10aeac.png)
_View of the base_link and the wheels_

  
### Definition of done
 - [ ] Carpincho URDF file updated with the correct values.

**Comment by francocipollone** [comment]
Closing as it was part of the noetic branch which is not supported anymore
