### ISSUE TITLE
Set up Nav2

### ISSUE THREAD

**Issue by francocipollone** [Ekumen-OS/andino#48]
### Summary

Enable [nav2 navigation](https://github.com/ros-planning/navigation2) in Andino.

### Suggestions
 - [x] Provide an andino_navigation package.
 - [ ] Provide a basic launch file to bring up nav2: Check [nav2_bringup](https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/launch/bringup_launch.py) launch file.
      - A configuration file is expected to be added to a config folder within the package for setting up different nav2's systems and to be loaded by the launch file.
      - Probably some topics in Andino/Nav2 should be remapped (or relayed) 

### Extras

https://arxiv.org/abs/2307.15236

**Comment by agalbachicar** [comment]
@nahueespinosa there is an effort that is about to start now that will take care of this. Have you started it already? If so, let's join forces!

**Comment by nahueespinosa** [comment]
@francocipollone  In fact, I haven't started yet, but it should be very easy. I'll unassign myself then. Happy to help whoever is going to take care of this task.

**Comment by Voldivh** [comment]
I believe the issue description provide the necessary tasks needed to complete the feature. I would just like to complete it with a couple of comments related to the scope of the effort that is starting:
- The implementation of the nav2 is related to be on top of the Andino simulation in Gazebo, taking into account the completion of #47.
- We are expecting to use the whole nav2 library in order to do localization, planning, navigation, etc. However, we would also like to assess the possibility of using Beluga in order to replace nav2_amcl. I think this should be assessed in terms of the amount of time that implementation would take. @nahueespinosa Could you provide us some insight about this topic?

**Comment by agalbachicar** [comment]
To the best of my knowledge, @francocipollone did something already with it.

**Comment by nahueespinosa** [comment]
> However, we would also like to assess the possibility of using Beluga in order to replace nav2_amcl.
> ...
> Could you provide us some insight about this topic?

We already did this, here is a branch with example launch files https://github.com/Ekumen-OS/beluga/pull/213.

To start setting up localization with `nav2_amcl`, I'd recommend using this file as reference: https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/launch/localization_launch.py

`beluga_amcl` is a drop-in replacement, so once `nav2_amcl` is working, it is only a matter of installing Beluga from source and replacing the localization node name in a launch file.

@francocipollone got `slam_toolbox` working as well.

**Comment by francocipollone** [comment]
I would start by setting up Nav2 as it is, once that is working we can parallel the work in order to choose `beluga` as the replacement for `nav2_amcl`. `Beluga`'s binaries are not yet released via ROS 2 build farm so it demands an extra step of building the library. For the simulation, we can simply add this step to the dockerfile. For the real robot it is necessary to bring the repo and build it.

> @francocipollone got slam_toolbox working as well.

I will push some stuff to launch `slam_toolbox` https://github.com/Ekumen-OS/andino/issues/49 shortly

PS: Thanks @nahueespinosa for the `beluga`'s info :rocket:

**Comment by agalbachicar** [comment]
I know @olmerg did some progress on this yesterday.
CC @elector102 as you may also help here.

**Comment by olmerg** [comment]
this is the initial branch [olmerg/nav2_gazebo](https://github.com/Ekumen-OS/andino/tree/olmerg/nav2_gazebo).

Which is expected in this package?

**Comment by hidmic** [comment]
Is this complete @francocipollone ?

**Comment by francocipollone** [comment]
Superseded by #190
