### ISSUE TITLE
Improve firmware code base

### ISSUE THREAD

**Issue by jballoffet** [Ekumen-OS/andino#87]
## Desired behavior
Firmware code base shall be improved so as to ease its maintenance, decouple logic and drivers code (to ease the process of using a different dev board / microcontroller) and add unit tests.

**Comment by elector102** [comment]
I can work on that! I have some experience and I made some investigation before for noah.

**Comment by jballoffet** [comment]
Hi Fabri! I'm currently working on it, I will sync with you later on the lessons learned from the noahbot. Thanks for the heads up!

**Comment by JesusSilvaUtrera** [comment]
@jballoffet we should close this issue since the PRs for improving the firmware were already merged.

**Comment by jballoffet** [comment]
I concur, this can be closed now. Thanks!
