### ISSUE TITLE
Add ClangFormat config file

### ISSUE THREAD

**Issue by jballoffet** [Ekumen-OS/andino#90]
## Desired behavior
It would be nice to have a ClangFormat config file within the andino_firmware folder.

**Comment by francocipollone** [comment]
If it helps for the implementation, note there is a clang-format file at https://github.com/Ekumen-OS/andino/blob/humble/andino_base/.clang-format

And this can be executed via https://github.com/Ekumen-OS/andino/blob/humble/andino_base/tools/formatter.sh script
