### ISSUE TITLE
Wheel size does not match description/controller

### ISSUE THREAD

**Issue by BarceloChristian** [Ekumen-OS/andino#93]
## Environment
* OS Version: 
* Source or binary build?
  
  

## Description
* Expected behavior:
  - Wheel size is defined the same across all the stack
* Actual behavior:
  - Wheel **Diameter** is defined to 0.035 for Gazebo's diff drive plugin ([here](https://github.com/Ekumen-OS/andino/blob/humble/andino_gazebo/urdf/andino.gazebo.xacro#L75))
  - Wheel **Radius** is defined to 0.0331 ([here](https://github.com/Ekumen-OS/andino/blob/humble/andino_description/config/andino/wheel.yaml#L2))

**Comment by elector102** [comment]
@BarceloChristian @francocipollone what is the real value?

**Comment by francocipollone** [comment]
> @BarceloChristian @francocipollone what is the real value?

The real value of the **Diameter** is 6.6 cm

**Comment by agalbachicar** [comment]
@JesusSilvaUtrera will take care right away of this task as he gets to know the platform and this seems to be great issue to begin with.

**Comment by JesusSilvaUtrera** [comment]
I have created this [https://github.com/Ekumen-OS/andino/pull/230](PR) for this issue
